# Generated by Django 4.2 on 2023-12-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='plataform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wathlist', to='core.streamplataform'),
            preserve_default=False,
        ),
    ]
