# Generated by Django 4.2 on 2023-12-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_watchlist_plataform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='core.streamplataform'),
        ),
    ]
